Tela detalhes integracao
suspsaude/susp pull request #17
Opened 2024-11-07 20:10 UTC by octopus-me

2024-11-10 19:19 UTC, th-duvanel requested changes
Acredito que faltam algumas informações importantes para aparecerem na tela de detalhes, considerando que o back-end disponibiliza várias informações e poucas foram usadas:

Ainda falta:
- Endereço completo (com CEP)
- Tipo da unidade
- Email (caso tenha)
- Lista com todos os serviços oferecidos, que é oferecida pelo back-end também.

A adição de tudo isso vai deixar a tela mais preenchida.

Além disso, acredito que o mapa esteja estranho: o marcador está aparecendo como "Marker" e não uma imagem. Talvez isso seja um problema de dependência local meu - caso não seja, acho legal colocar um marcador colorido pois nossa tela de detalhes é bicolor (branco e azul).

2024-11-10 23:46 UTC, octopus-me commented
Preciso saber a forma como essa Lista de todos os serviços oferecidos vai ser disponibilizado na tela. As demais mudanças já foram alteradas.

2024-11-11 19:26 UTC, th-duvanel commented
Teste um número cnes qualquer no swagger, vai mostrar exatamente como sai.

Caso precise, no nosso grupo de desenvolvimento também tem uma imagem que mostra a saída exata.
________________________________
From: Guilherme Wallace ***@***.***>
Sent: Sunday, November 10, 2024 8:46:27 PM
To: suspsaude/susp ***@***.***>
Cc: Thiago Duvanel ***@***.***>; Review requested ***@***.***>
Subject: Re: [suspsaude/susp] Tela detalhes integracao (PR #17)


Preciso saber a forma como essa Lista de todos os serviços oferecidos vai ser disponibilizado na tela. As demais mudanças já foram alteradas.

—
Reply to this email directly, view it on GitHub<https://github.com/suspsaude/susp/pull/17#issuecomment-2466991553>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZPFQA6T4HROLP3RNO2C5DTZ77V5HAVCNFSM6AAAAABRMACXGWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINRWHE4TCNJVGM>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-11-14 11:13 UTC, octopus-me commented
Eu sei que tem os dados ao fazer a busca pelo número do CNES, eu quero dizer que não foi definido como seria a interface de exibição dessas informações de serviços oferecidos na tela.

2024-11-20 00:39 UTC, th-duvanel commented
Consertado alguns erros da branch e mergeado para dev.
Obrigado!

2024-11-20 00:39 UTC, merged